source $HOME/.profile
alias gst="git status";
alias gco="git checkout";
alias gc="git commit";
alias gb="git branch";
alias gp="git pull";
alias gr="git rebase";
alias k="kubectl";
export EDITOR="nvim";
export NIXPKGS_ALLOW_UNFREE=1
PATH="$PATH:/usr/bin/local:$HOME/miniconda3/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:$HOME/.rd/bin";
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias gst="git status"
alias gco="git checkout"
alias emacs="/Applications/Emacs.app/Contents/MacOS/Emacs -nw"
alias dco="docker-compose"
alias k="kubectl"
alias ll="ls -la"
